#############################################################################
# Gitlab CI/CD Configuration File
#############################################################################
# Author: Dave Askew (based on the work of Brandon Smith)
#############################################################################

# Build stages
# -------------------------------------------------------------------
# -- NOTE: We can define a stage here that does not have an attached
#    job. -- DA
#
stages:
  - Setup
  - Build
  - Deploy

# Include Gitlab CI/CD Common
# -------------------------------------------------------------------
# This section imports CI/CD job templates from a common repository.  
# This effort should benefit us in a number of ways:
# * Reduce cut-and-paste errors between projects
# * Improve configuration readability
# * Make configuration maintenance easier 
# * Make it easier to expand a configuration to cover a new OS
#
include:
  - project: 'CyberRadioDriver/development/gitlab-cicd-common'
    file:
      - '/config/ubuntu16.yml'
      - '/config/ubuntu18.yml'
      - '/config/ubuntu20.yml'
      - '/config/centos7.yml'
      - '/config/fedora28.yml'
      - '/scripts/setup/environment.yml'
      - '/scripts/build/debian.yml'
      - '/scripts/build/redhat.yml'
      - '/scripts/deploy/apt.yml'
      - '/scripts/deploy/yum.yml'
      - '/scripts/deploy/ftp.yml'

#####################################################
# Common
#####################################################

# Setup (All)
# -------------------------------------------------------------------
# Use the following variables to tailor the setup configuration for a 
# given project:
# * PKG_REPO_SERVER: Apt/yum repository server
#   -- default: asterix.mamd.g3ti.local
# * PKG_TARGET_DISTROS: Target distributions for apt/yum deployment
#   -- NOTE: The default for this depends on the attached OS configura-
#      tion.  If you set this, make sure that it makes sense for the 
#      OS that you are building against. 
#   -- default: xenial (for Ubuntu 16 configuration)
# * FTP_SERVER: FTP server
#   -- default: asterix.mamd.g3ti.local
# * FTP_REMOTE_DIR_BASE: FTP remote directory base
#   -- NOTE: This should be unique for each project!
#   -- default: jenkins_pub
# * BUILD_PYTHON2: Build Python packages against Python 2?
#   -- NOTE: The attached OS configuration sets this as appropriate 
#      for the given OS.  Be careful if you override this setting.
# * BUILD_PYTHON3: Build Python packages against Python 3?
#   -- NOTE: The attached OS configuration sets this as appropriate 
#      for the given OS.  Be careful if you override this setting.
# * PKG_MANAGER: Package management program
#   -- NOTE: The attached OS configuration sets this as appropriate 
#      for the given OS.  Be careful if you override this setting.
# * PKG_DOWNLOAD: Package download command
#   -- NOTE: The attached OS configuration sets this as appropriate 
#      for the given OS.  Be careful if you override this setting.
#
.setup-build-environment-ours:
    extends:
    - .setup-build-environment
    variables:
        # FTP remote directory base
        FTP_REMOTE_DIR_BASE: jenkins_pub/libcyberradio

# Build (Debian and Red Hat)
# -------------------------------------------------------------------
# Use the following variables to tailor the build configuration for a 
# given project:
# * BUILD_DEPS: Build dependencies; that is, packages that the build 
#   step needs to install before trying to build the software
#   -- default: [empty string]
# * TARBALL_DEPS: Tarball dependencies; that is, for projects that 
#   build tarballs as artifacts, packages that this step needs to 
#   download and package with the tarball(s)
#   -- default: [empty string]
#
# When you construct the build script, base it on the following functions:
# * section_banner -- Prints a section banner with the given label
# * exit_if_error [code] -- Exits if the code is non-zero
# * install_or_upgrade [files] -- Installs/upgrades packages from
#   the given file(s)
# * build_package [pkg] [dir] -- Builds a deb package from a source 
#   directory
# * build_and_install_package [pkg] [dir] -- Builds a package from 
#   a source directory and installs it into the build environment
# * build_python_packages [pkg] [dir] -- Builds packages from a 
#   Python source directory.  This function uses BUILD_PYTHON2 and 
#   BUILD_PYTHON3 to decide what Python versions to build against.
# * build_and_install_python_packages [pkg] [dir] -- Builds packages 
#   from a Python source directory and installs them into the build
#   environment.  This function uses BUILD_PYTHON2 and BUILD_PYTHON3 to 
#   decide what Python versions to build against.
# * is_package_version_lt [ver] [tar] -- Is a package version string
#   less than a given target version?
# * is_package_version_gt [ver] [tar] -- Is a package version string
#   greater than a given target version?
# * is_package_version_eq [ver] [tar] -- Is a package version string
#   equal to a given target version?
# * is_package_version_le [ver] [tar] -- Is a package version string
#   less than or equal to a given target version?
# * is_package_version_ge [ver] [tar] -- Is a package version string
#   greater than or equal to a given target version?

.build-debian-ours:
    extends:
    - .build-debian
    variables:
        BUILD_DEPS: "g3-makedeb dh-python"
        TARBALL_DEPS: ""
    script: |-
        section_banner "Building Packages"
        build_package libcyberradio libcyberradio

.build-redhat-ours:
    extends:
    - .build-redhat
    variables:
        BUILD_DEPS: "g3-makerpm"
        TARBALL_DEPS: ""
    script: |-
        section_banner "Building Packages"
        build_package libcyberradio libcyberradio
        # This build_package step also creates -devel and -doc packages,
        # so move those into GITLAB, too
        mv libcyberradio-devel-[0-9]*.rpm GITLAB
        mv libcyberradio-doc-[0-9]*.rpm GITLAB

#####################################################
# Ubuntu 16
#####################################################

# Setup (U16)
# -------------------------------------------------------------------
#
setup-u16:
    stage: Setup
    extends:
    - .ubuntu-16
    - .setup-build-environment-ours

# Build (U16)
# -------------------------------------------------------------------
#
build-u16:
    stage: Build
    extends:
    - .ubuntu-16
    - .build-debian-ours
    dependencies:
    - setup-u16

# Deploy FTP (U16)
# -------------------------------------------------------------------
#
deploy-ftp-u16:
    stage: Deploy
    extends:
    - .ubuntu-16
    - .deploy-ftp
    dependencies:
    - build-u16

# Deploy APT (U16)
# -------------------------------------------------------------------
#
deploy-apt-u16:
    stage: Deploy
    extends:
    - .ubuntu-16
    - .deploy-apt
    dependencies:
    - build-u16

#####################################################
# Ubuntu 18
#####################################################

# Setup (U18)
# -------------------------------------------------------------------
#
setup-u18:
    stage: Setup
    extends:
    - .ubuntu-18
    - .setup-build-environment-ours

# Build (U18)
# -------------------------------------------------------------------
#
build-u18:
    stage: Build
    extends:
    - .ubuntu-18
    - .build-debian-ours
    dependencies:
    - setup-u18

# Deploy FTP (U18)
# -------------------------------------------------------------------
#
deploy-ftp-u18:
    stage: Deploy
    extends:
    - .ubuntu-18
    - .deploy-ftp
    dependencies:
    - build-u18

# Deploy APT (U18)
# -------------------------------------------------------------------
#
deploy-apt-u18:
    stage: Deploy
    extends:
    - .ubuntu-18
    - .deploy-apt
    dependencies:
    - build-u18

#####################################################
# Ubuntu 20
#####################################################

# Setup (U20)
# -------------------------------------------------------------------
#
setup-u20:
    stage: Setup
    extends:
    - .ubuntu-20
    - .setup-build-environment-ours

# Build (U20)
# -------------------------------------------------------------------
#
build-u20:
    stage: Build
    extends:
    - .ubuntu-20
    - .build-debian-ours
    dependencies:
    - setup-u20

# Deploy FTP (U20)
# -------------------------------------------------------------------
#
deploy-ftp-u20:
    stage: Deploy
    extends:
    - .ubuntu-20
    - .deploy-ftp
    dependencies:
    - build-u20

# Deploy APT (U20)
# -------------------------------------------------------------------
#
deploy-apt-u20:
    stage: Deploy
    extends:
    - .ubuntu-20
    - .deploy-apt
    dependencies:
    - build-u20

#####################################################
# CentOS 7
#####################################################

# Setup (C7)
# -------------------------------------------------------------------
#
setup-c7:
    stage: Setup
    extends:
    - .centos7
    - .setup-build-environment-ours

# Build (C7)
# -------------------------------------------------------------------
#
build-c7:
    stage: Build
    extends:
    - .centos7
    - .build-redhat-ours
    dependencies:
    - setup-c7

# Deploy FTP (C7)
# -------------------------------------------------------------------
#
deploy-ftp-c7:
    stage: Deploy
    extends:
    - .centos7
    - .deploy-ftp
    dependencies:
    - build-c7

# Deploy YUM (C7)
# -------------------------------------------------------------------
#
deploy-yum-c7:
    stage: Deploy
    extends:
    - .centos7
    - .deploy-yum
    dependencies:
    - build-c7

#####################################################
# Fedora 28
#####################################################

# Setup (F28)
# -------------------------------------------------------------------
#
setup-f28:
    stage: Setup
    extends:
    - .fedora28
    - .setup-build-environment-ours

# Build (F28)
# -------------------------------------------------------------------
#
build-f28:
    stage: Build
    extends:
    - .fedora28
    - .build-redhat-ours
    dependencies:
    - setup-f28

# Deploy FTP (F28)
# -------------------------------------------------------------------
#
deploy-ftp-f28:
    stage: Deploy
    extends:
    - .fedora28
    - .deploy-ftp
    dependencies:
    - build-f28

# Deploy YUM (F28)
# -------------------------------------------------------------------
#
deploy-yum-f28:
    stage: Deploy
    extends:
    - .fedora28
    - .deploy-yum
    dependencies:
    - build-f28
