name: libcyberradio build

on:
  push:
    branches: [ main, test_workflow ]
  #pull_request:
  #  branches: [ main ]

jobs:
  # build-ubuntu18-04:
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk1-dev libvolk1.3
  #   - run: cd libcyberradio/ && mkdir build && cd build && cmake ../ && make -j 10
  # release-ubuntu18-04:
  #   needs: ['build-ubuntu18-04']
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk1-dev libvolk1.3
  #   - run: sudo apt-get install build-essential devscripts debhelper doxygen dh-python
  #   - run: ./makedeb libcyberradio
  # build-ubuntu20-04:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk2-dev libvolk2.2
  #   - run: cd libcyberradio/ && mkdir build && cd build && cmake ../ && make -j 10
  # release-ubuntu20-04:
  #   needs: ['build-ubuntu20-04']
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk2-dev libvolk2.5
  #   - run: sudo apt-get install build-essential devscripts debhelper doxygen dh-python
  #   - run: ./makedeb libcyberradio
  build-ubuntu22-04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk2-dev libvolk2.5
    - run: cd libcyberradio/ && mkdir build && cd build && cmake ../ && make -j 10
  release-ubuntu22-04:
    needs: ['build-ubuntu22-04']
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk2-dev libvolk2.5
    - run: sudo apt-get install build-essential devscripts debhelper doxygen dh-python
    - run: ls -lha
    - run: ./makedeb libcyberradio
