name: libcyberradio build

on:
  push:
    branches: [ main, test_workflow ]
  #pull_request:
  #  branches: [ main ]

jobs:
#   build-ubuntu18-04:
#     runs-on: ubuntu-18.04
#     steps:
#     - uses: actions/checkout@v2
#     - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk1-dev libvolk1.3 cmake
#     - run: cd libcyberradio/ && mkdir build && cd build && cmake ../ && make -j 10
#   release-ubuntu18-04:
#     needs: ['build-ubuntu18-04']
#     runs-on: ubuntu-18.04
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install Build Deps
#       run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk1-dev libvolk1.3
#     - name: Install Package Deps
#       run: sudo apt-get install build-essential devscripts debhelper doxygen dh-python cmake
#     - name: Save Debian Archive
#       run: ./makedeb libcyberradio
#     - name: Save Debian Archive
#       uses: actions/upload-artifact@v3
#       with:
#         name: libcyberradio_ubuntu_bionic
#         path: ./*.deb
  build-ubuntu20-04:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk2-dev libvolk2.2 cmake 
    - run: cd libcyberradio/ && mkdir build && cd build && cmake ../ && make -j 10
  release-ubuntu20-04:
    needs: ['build-ubuntu20-04']
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Build Deps
      run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk2-dev libvolk2.2
    - name: Install Package Deps
      run: sudo apt-get install build-essential devscripts debhelper doxygen dh-python cmake 
    - name: Build and Package
      run: ./makedeb libcyberradio
    - name: Save Debian Archive
      uses: actions/upload-artifact@v3
      with:
        name: libcyberradio_ubuntu_focal
        path: ./*.deb
  build-ubuntu22-04:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk2-dev libvolk2.5 cmake
    - run: cd libcyberradio/ && mkdir build && cd build && cmake ../ && make -j 10
  release-ubuntu22-04:
    needs: ['build-ubuntu22-04']
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Build Deps
      run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk2-dev libvolk2.5
    - name: Install Package Deps
      run: sudo apt-get install build-essential devscripts debhelper doxygen dh-python cmake
    - name: Build Package
      run: ./makedeb libcyberradio
    - name: Save Debian Archive
      uses: actions/upload-artifact@v3
      with:
        name: libcyberradio_ubuntu_jammy
        path: ./*.deb

  build-ubuntu24-04:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk-dev libvolk-bin cmake
    - run: cd libcyberradio/ && mkdir build && cd build && cmake ../ && make -j 10
  release-ubuntu24-04:
    needs: ['build-ubuntu24-04']
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Build Deps
      run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libjsoncpp-dev libboost-all-dev libvolk-dev libvolk-bin
    - name: Install Package Deps
      run: sudo apt-get install build-essential devscripts debhelper doxygen dh-python cmake
    - name: Build Package
      run: ./makedeb libcyberradio
    - name: Save Debian Archive
      uses: actions/upload-artifact@v3
      with:
        name: libcyberradio_ubuntu_nobel
        path: ./*.deb

